server:
  port: 9050

logging:
  level:
    org:
      springframework:
        security: DEBUG
  file:
    name: ${LOG_PATH:logs/expense-service.log}
    path: ${LOG_PATH:logs/expense-service.log}

spring:
  application:
    name: expenservice

  jackson:
    property-naming-strategy: SNAKE_CASE

  flyway:
    locations: classpath:/db/migration
    schemas: ${DB_SCHEMA:transaction}
    baselineOnMigrate: true
    enabled: true
    validateOnMigrate: true
    validate-migration-naming: true
    clean-on-validation-error: true
    clean-disabled: false

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:expenservice}?currentSchema=${DB_SCHEMA:transaction}
    username: ${DB_USERNAME} # rajsubhod
    password: ${DB_PASSWORD} # password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    consumer:
      group-id: ${KAFKA_GROUP_ID:2}
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost}:${KAFKA_BOOTSTRAP_PORT:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.rajsubhod.expenseservice.deserializer.ExpenseDeserializer
      auto-offset-reset: earliest
    topic:
      name: ${KAFKA_TOPIC_NAME:transaction}
